help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist outputs
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	find . | grep -E ".coverage*" | xargs rm -rf
	rm -f .coverage

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git fetch -p
	git pull origin main
	poetry install

update-dev: ## Update development dependencies
	poetry update --only dev
	poetry install

build: ## Build docker image from dockerfile
	DOCKER_BUILDKIT=1 docker build \
		-f Dockerfile \
		--network=host \
		-t hse_news_image .

run: ## Create docker container from image and run
	docker run -dit \
		--name hse_news_container \
		-p 127.0.0.1:8000:8080 \
		--network host \
		hse_news_image /bin/bash

start: ## Start created container
	docker start hse_news_container

stop: ## Stop running container
	docker stop hse_news_container
